# Generated by Django 3.1.12 on 2025-09-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
