# Generated by Django 3.1.12 on 2025-08-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
