# Generated by Django 3.1.12 on 2025-09-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='project',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='location',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='website_url',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='selected_template',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
